apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: helloworld
    spec: 
      containers:
        - name: Kubetraining
          image: lnanditha/kubetraining
          ports:
            - name: nodejs-port
              containerPort: 3000
